version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rpks4_db
    environment:
      POSTGRES_DB: rpks4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rpks4"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: